version: "3.9"

services:
  backend:
    build:
      context: ./backend
    environment:
      - MODE=${MODE:-normal}
      - EXFIL_URL=${EXFIL_URL:-https://example.com:4444/steal}
      - PAYMENTS_URL=${PAYMENTS_URL:-http://payments-internal:8080/reconcile}
    ports:
      - "8000:8000"
    networks:
      - bachat

  frontend:
    build:
      context: ./frontend
    environment:
      - VITE_BACKEND_URL=${VITE_BACKEND_URL:-http://13.204.239.189:8000}
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - bachat

networks:
  bachat:
    name: bachat

